POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo":"aprende node js",
    "lenguaje": "javascript",
    "vistas": 45768,
    "nivel": "basico"
}


###

PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "Python intermedio ccon proyectos",
    "lenjuage": "python",
    "vistas": 123996,
    "nivel": "intermedio"
}